name: "Bug report"
description: "Report a bug or unexpected behavior in this project."
labels: "type:bug"
type: "Bug"
body:
    - type: markdown
      attributes:
          value: |
              👋 Thank you for taking the time to report a bug! Please fill out as much of this template as you can — the more details you provide, the easier it will be for us to investigate and fix the issue.
              
              ⚠️ *Please search existing issues before filing a new one.*
              
    - type: textarea
      attributes:
          label: Describe the bug
          description: |
              Provide a clear and concise description of the bug:
              
              - What is happening?
              - What did you expect to happen?
              - If relevant, what error messages are shown?
          placeholder: |
              Example:
              When I try to use the 'Save' feature, I get an error message: "Failed to save file." 
              I expect the file to save successfully without errors.
      validations:
          required: true
          
    - type: textarea
      attributes:
          label: Steps to Reproduce
          description: |
              Provide step-by-step instructions to reproduce the issue.
              
              Example:
              1. Go to 'File' menu
              2. Click on 'Save As'
              3. Enter filename and click 'Save'
              4. See error message
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, or code snippet
          description: |
              If possible, attach a screenshot, screen recording, or code snippet that shows the bug.
              
              👉 Tip: Drag and drop images or log files here, or paste code snippets directly.
              
              For multiple files, consider using [GitHub Gist](https://gist.github.com).
      validations:
          required: false
          
    - type: textarea
      attributes:
          label: Environment information
          description: |
              Provide details about your environment to help us reproduce the issue.
          placeholder: |
             - Device: e.g. MacBook Pro
             - OS: e.g. macOS 14.0
             - Browser and version: e.g. Chrome 123.0.4567.89, Firefox 115.0
             - App version (if applicable): e.g. 1.2.3
      validations:
          required: false
          
    - type: checkboxes
      id: terms
      attributes:
        label: Code of Conduct
        description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).
        options:
          - label: I agree to follow this project's Code of Conduct
            required: true
